### ISSUE TITLE
"New Packages" feed: show newest first

### ISSUE THREAD

**Issue by kaushalmodi** [FedericoCeratto/nim-package-directory#14]
Hello,

I was checking out the https://nimble.directory/ site today, and was excited to see that it provided an RSS feed for new packages: https://nimble.directory/packages.xml

But the feed is not showing the newest packages first; it looks like this:

![image](https://user-images.githubusercontent.com/3578197/44365170-01157300-a497-11e8-9d03-83e5b79eacbd.png)

**Comment by FedericoCeratto** [comment]
Related: #25
