### ISSUE TITLE
add "Report package" button

### ISSUE THREAD

**Issue by samdmarshall** [FedericoCeratto/nim-package-directory#26]
today i was trying to find a package for a personal project, and came across the [htmlview](https://nimble.directory/pkg/htmlview) package. this package seems to have been deleted by the author, and never updated in the index as to have it removed entirely or redirected to the new repo. On the individual package page on `https://nimble.directory/pkg/...` there seems to be no way to report a problem with said package.

* If the package **doesn't** have a public visible repo/source then there should be a link to create a new PR to remove the package from [package index](https://github.com/nim-lang/packages/). that process should be able to be 100% automated/scripted.
* If the package **does** have a public visible repo/source then there should be either a link to create a new issue on the package repo (if using github or another similar SCM system) or a mailing address for the author or to the package's mailing-list to correspond about the problem. (this may require some changes to the submission guidelines regarding new and existing packages so that non-github hosted packages provide some way of contacting the package author).

To mitigate similar future issues, perhaps a scheduled job should be added the package index CI system to validate that package sources aren't 404'ing in addition to validating that any new packages added are valid JSON or whatever.

/cc @dom96 as you originally created the package index and since it's now part of the language org, i assume you have some say in how package validation happens and if it is part of a nightly CI job or something.

**Comment by FedericoCeratto** [comment]
This is an issue for https://github.com/nim-lang/packages and the package directory is not authoritative on the contents of the package list. There are already some CI jobs in that archive to help manage the package list.
