### ISSUE TITLE
Site crashes if you search "Http"

### ISSUE THREAD

**Issue by moigagoo** [FedericoCeratto/nim-package-directory#32]
Visiting this URL returns an error with routes: https://nimble.directory/search?query=Http

**Comment by moigagoo** [comment]
An error has occured in one of your routes.
Detail: package_directory.nim package_directory
package_directory.nim main
jester.nim serve
httpbeast.nim run
httpbeast.nim eventLoop
httpbeast.nim processEvents
jester.nim :anonymous
jester.nim handleRequest
jester.nim dispatch
asyncmacro.nim dispatchNimAsyncContinue
asyncmacro.nim dispatchIter
jester.nim mainRouter
asyncmacro.nim mainRouterNimAsyncContinue
asyncmacro.nim mainRouterIter
tables.nim []
tables.nim []
[[reraised from:
package_directory.nim package_directory
package_directory.nim main
jester.nim serve
httpbeast.nim run
httpbeast.nim eventLoop
httpbeast.nim processEvents
jester.nim :anonymous
jester.nim handleRequest
jester.nim dispatch
asyncmacro.nim dispatchNimAsyncContinue
asyncmacro.nim dispatchIter
asyncfutures.nim read
]]
[[reraised from:
package_directory.nim package_directory
package_directory.nim main
jester.nim serve
httpbeast.nim run
httpbeast.nim eventLoop
httpbeast.nim processEvents
jester.nim :anonymous
jester.nim handleRequest
jester.nim handleRequestSlow
asyncmacro.nim handleRequestSlowNimAsyncContinue
asyncmacro.nim handleRequestSlowIter
asyncfutures.nim read
]]
key not found: cookies

**Comment by FedericoCeratto** [comment]
It's working at the moment and the traceback does not indicate where the offending line is.

**Comment by FedericoCeratto** [comment]
I updated the webapp to show line numbers.

**Comment by moigagoo** [comment]
Thanks! I think it's safe to close the issue since the page opens OK.

**Comment by moigagoo** [comment]
I'll close the issue for now and if it reproduces in the future, it can be reopened.
