### ISSUE TITLE
Lists in descriptions have the same color in dark mode as light mode

### ISSUE THREAD

**Issue by hlaaftana** [FedericoCeratto/nim-package-directory#33]
![image](https://user-images.githubusercontent.com/10591326/99702087-702f0700-2aa6-11eb-81db-4e91ba71f9c7.png)

**Comment by FedericoCeratto** [comment]
Fixed. Thank you.

**Comment by digitalcraftsman** [comment]
The same applies to text in tables, e.g. [here](https://nimble.directory/pkg/pixie).

![grafik](https://user-images.githubusercontent.com/7010165/143722517-01a4559c-610c-46a5-b3a6-7d313f66d95a.png)
