### ISSUE TITLE
README not taken from repository

### ISSUE THREAD

**Issue by ehmry** [FedericoCeratto/nim-package-directory#35]
READMEs are fetched from a github API and not from repositories themselves, so everything not hosted on github shows "Package … doesn't contains a README file.", which is incorrect.

**Comment by ArMour85** [comment]
I have the same problem with my package **checkpack** on GitLab.

**Comment by FedericoCeratto** [comment]
The current implementation uses the HTML content rendered by github. Unfortunately software forges do their own, custom rst/asciidoc/markdown rendering and still don't expose a common API to handle such content.

**Comment by ArMour85** [comment]
You can't code support all API because it's never ending, but you can do without.

You can get some information with `git ls-remote`:
```bash
$ git ls-remote https://gitlab.com/ArMour85/checkpack.git
38d0aedf85111847c654ffa0f4607ee7a867b6af        HEAD
c6a20b7734bee53b08f2e536926839fa2bdde2cc        refs/heads/feature/add-apt
a03bd01e021ca7b75bf362c31791dfddfb4d10ce        refs/heads/feature/add-dnf
38d0aedf85111847c654ffa0f4607ee7a867b6af        refs/heads/master
619cf714aa9a7b74c16e8c466da9efee17ee0a19        refs/tags/0.1.0
6e6b1210f7882cdaeafd157021a1c02c1b692ead        refs/tags/0.1.0^{}
6f86be44853a0c1f4ffdb650b2442dd1037122a7        refs/tags/0.1.1
38d0aedf85111847c654ffa0f4607ee7a867b6af        refs/tags/0.1.1^{}
```

With this information, you clone the latest tag if it exists in the good form or directly the master branch:
```bash
git clone --depth 1 --branch 0.1.1 https://gitlab.com/ArMour85/checkpack.git
```

So, now you can read the README, and extract from .nimble file the version and the license.

I don't know if you have all needed information with this method.

**Comment by m33m33** [comment]
Alternatively, you may just get the README.md file (url are predictable) and give it to pandoc to get an html rendering of the content.

Something like:

```
curl $doc/-/raw/master/README.md > README.md
pandoc README.md -t html -o README.html
```

**Comment by ehmry** [comment]
Right now READMEs are text files stored in the root of package repositories.

Would it be better if the URL of README was explicitly specificied in the Nimble file?

**Comment by m33m33** [comment]
> Right now READMEs are text files stored in the root of package repositories.
> 
> Would it be better if the URL of README was explicitly specified in the Nimble file?

That would save the work to guess the git repo type, and the logic to get to the readme file right?

**Comment by ehmry** [comment]
bump

Either fix your shit or don't index my packages with wrong information.

**Comment by zetashift** [comment]
It seems non-trivial to add support for all kinds of forges like Gitlab/BitBucket etc, a compromise here might be to change the `Package … doesn't contains a README file` text if it's a non github repo;

For example:

`Visit [package homepage] for more info` or something.
