### ISSUE TITLE
Hosted docs not displaying at all

### ISSUE THREAD

**Issue by dizzyliam** [FedericoCeratto/nim-package-directory#44]
Looks like the hosted docs aren't displaying at all, even for packages where they build OK.

For an example, go to [https://nimble.directory/docs/flower](https://nimble.directory/docs/flower), then click `/flower`, to be taken to a blank page. In the page source I can see a hidden message saying _"Sorry, that file does not exists."_ Seems to behave the same for all packages.

**Comment by FedericoCeratto** [comment]
Thank you for the report! It's fixed now.
