### ISSUE TITLE
Nimble Into the Wild - Design ideas, talks, and previews

### ISSUE THREAD

**Issue by georgelemon** [FedericoCeratto/nim-package-directory#47]
Hey, I want to contribute with ideas, code and design for a better looking Nimble!

<img width="1522" alt="Screenshot 2022-02-09 at 10 58 23 PM" src="https://user-images.githubusercontent.com/1230420/153289578-12c7cab8-c670-47ed-9d7e-a6b852166efc.png">

<img width="1522" alt="Screenshot 2022-02-09 at 11 00 26 PM" src="https://user-images.githubusercontent.com/1230420/153289593-963d8007-d452-41eb-b6ff-d73cadd5c376.png">

**Comment by FedericoCeratto** [comment]
@georgelemon Thank you! Would you be interested in contributing a PR? If so, be aware that I'm trying to remove the dependency on CDNs, external fonts and maybe even the amount of js libraries.

**Comment by georgelemon** [comment]
Working on landing page and artworks.

I would remove jquery too. I can help with vanilla JS for writing a lightweight syntax highlighter and other cool things.

Ideas:
Focus on spotlight search with `/`.
Search should have autocomplete, powered by IndexedDB. So users will use data from their browser, no more n requests.
Nimble logo is floating (CSS)

I think I should post on Nim forum maybe we can catch some feedback and more ideas.

![01](https://user-images.githubusercontent.com/1230420/154067299-f602ecbe-03d7-414b-8517-229c9cfbe4c7.png)
![02](https://user-images.githubusercontent.com/1230420/154067313-2b3ab5e7-e45f-47af-a501-2b78ec315d0a.png)
![03](https://user-images.githubusercontent.com/1230420/154067318-c9ef4bf5-efcd-4c01-abd7-f8268bd7073d.png)

**Comment by georgelemon** [comment]
Light theme (to be embedded in forum discussion)
![04](https://user-images.githubusercontent.com/1230420/154221768-f201b167-ee63-4188-8afa-56c99907360d.png)

**Comment by digitalcraftsman** [comment]
The designs look awesome. Thanks @georgelemon for offering you design skills to the Nim community 👍


One small idea for improvement: the linked tags below the search box do not have the best contrast. In dark mode the text could have slightly gray-ish border to make them more visible. In the bright theme the tage name does not have much contrast to the backgroud; a darker font color might help.

**Comment by PMunch** [comment]
What's the  status on this?

**Comment by georgelemon** [comment]
The HTML/CSS/JS part is almost done. Will try find some time for final tweaks. Still, need someone to implement the new look (the current source code is too messy for me).

Also, It would be great to have a repo for the static version, maybe on @nim-lang page? Just to keep things in order.

**Comment by Willyboar** [comment]
@georgelemon It would be nice to use your template engine instead of source code filters.

**Comment by tandy-1000** [comment]
This looks beautiful! Can't wait for this to get implemented.

**Comment by georgelemon** [comment]
@Willyboar Oh yes! But Tim is still work in progress on parser/ast side and is pretty unusable right now

**Comment by Willyboar** [comment]
@georgelemon also you can join Nim discord server if you. There is a webdev channel and more.

**Comment by FedericoCeratto** [comment]
If you want to contribute the restyling with a PR please do not add more build dependencies or browser-side imports from 3rd party websites.

**Comment by j-james** [comment]
Any update on this? I'd be happy to help implement it if you're still looking for someone.

**Comment by georgelemon** [comment]
@j-james, here you can find some drafts
https://github.com/georgelemon/nimble-website
