### ISSUE TITLE
Feature request: Repology support

### ISSUE THREAD

**Issue by CyberTailor** [FedericoCeratto/nim-package-directory#49]
To comply with [Repology's requirements](https://repology.org/docs/requirements), nimble.directory needs to export the following fields besides ones defined in `packages.json`:

- [ ] Package version
- [ ] Package upstream URL (`web` if defined, else `url`)
- [ ] *(optional)* Package maintainer(s)
- [ ] *(optional)* Aliases
- [ ] *(optional)* Build status page URL
- [ ] *(optional)* Documentation URL (`doc` if defined, else nimble.directory hosted docs)

**Comment by FedericoCeratto** [comment]
@CyberTailor can you please clarify the feature request? I assume you expect https://nimble.directory to publish a json file for Repology. Who is going to do the integration into Repology itself?

**Comment by CyberTailor** [comment]
> Who is going to do the integration into Repology itself?

I can volunteer.

**Comment by CyberTailor** [comment]
Closing because Nim packages do not qualify as a repository - there is no version tracking
