### ISSUE TITLE
Incorrect version for package bigints

### ISSUE THREAD

**Issue by rotu** [FedericoCeratto/nim-package-directory#50]
The [`bigints` package reports version 0.5.0](https://nimble.directory/pkg/bigints) (see screenshot), [but the latest version is 1.0.0](https://github.com/nim-lang/bigints/blob/d843ecfe1e2a62c3b0e29d211df09763da408cac/bigints.nimble#L3).

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/119948/180632586-6a17b81d-1dd8-4447-b773-8e1b60281e4b.png">

**Comment by metagn** [comment]
This is because bigints has not made a git tag for 1.0.0, so Nimble does not know about this version. The latest tag is 0.5.0.

**Comment by rotu** [comment]
@metagn Thank you.
The version is correct in the `.nimble` file, which I assumed was the authoritative source. https://github.com/nim-lang/bigints/blob/master/bigints.nimble

Does that version number play any role? Should there be some sanity check in the package directory?

**Comment by dlesnoff** [comment]
Please see issue #76
I have asked if we should use semver. It is unclear to me how the version number which feature should follow which feature.
There is for the moment very few features implemented. We all involve ourselves benevolently into it.

**Comment by rotu** [comment]
issue link: https://github.com/nim-lang/bigints/issues/76

> I have asked if we should use semver. It is unclear to me how the version number which feature should follow which feature.
> There is for the moment very few features implemented. We all involve ourselves benevolently into it.

Regardless of any future development with the bigints package, the version number *today* is confusing because of the mismatch between the .nimble file and what's on the package directory.

If you're saying the version was bumped prematurely, I'd be okay with pulling the .nimble file version back (even though I think SemVer frowns on decrementing version numbers)
