### ISSUE TITLE
Package failing due to outdated nim version

### ISSUE THREAD

**Issue by rotu** [FedericoCeratto/nim-package-directory#52]
My package build is failing with "Error: Unsatisfied dependency: nim (>= 1.6.0)". I expect packages to be built against 1.6.6 (which I believe is the current stable version).

https://nimble.directory/ci/badges/records/nimdevel/output.html

**Comment by theAkito** [comment]
> "Error: Unsatisfied dependency: nim (>= 1.6.0)"

Doesn't that include `1.6.6`?

https://github.com/rotu/nim-records/blob/f1ae07f13811eda064dd664fbb598f377f66730e/records.nimble#L10

The package specifically asked for this.

**Comment by rotu** [comment]
> I think I understand your problem now. The build is executed with a Nim version lower than `1.6.0`.

Exactly. This package does not build under `1.4.8`, and I think `1.6.0` is a reasonable version floor.

Also related is #15

**Comment by theAkito** [comment]
> I think `1.6.0` is a reasonable version floor.

I'm against the whole notion of keeping the version as low as possible for "compatibility" reasons or whatever excuse is used to not fix the software.

I have lots of experiences with the Java world and one of the worst things is this staying forever on low versions. People stay for so long on too low versions and then complain, that jumping 10 versions at once creates lots of issues...

I think, in regards to Nim specifically, it is absolutely reasonable to have every official stable version be a valid version floor.

**Comment by rotu** [comment]
> I'm against the whole notion of keeping the version as low as possible for "compatibility" reasons or whatever excuse is used to not fix the software.

I agree with you. Maybe I should have said that "I expect the package to be built against the latest stable release 1.6.6 and I am very surprised the current version is behind the latest feature release 1.6.x"

**Comment by FedericoCeratto** [comment]
I just updated the version of Nim on nimble.directory. Currently it is using 1.6.2

**Comment by rotu** [comment]
@FedericoCeratto
> I just updated the version of Nim on nimble.directory. Currently it is using 1.6.2

Thank you!

> As a side note, both the release train 1.2 and 1.4 are still alive and you should support at least the latter.
> See https://github.com/nim-lang/Nim/tags

1. The release announcement for 1.6.6 says "We would recommend to all of our users to upgrade and use version 1.6.6.". The [hosted documentation](https://nim-lang.org/docs/lib.html) is only published for devel (1.7.1) and stable (1.6.6). If it is expected for some users to start new projects in 1.4 for whatever reason, I'd expect that to be documented somewhere.
2. `nimble init` creates packages with 1.6.6.  (as you reported in https://github.com/nim-lang/nimble/issues/742)
3. The package directory does not check/show version compatibilities, so it's not obvious what versions you should expect a package to work with.
