### ISSUE TITLE
Badges broken

### ISSUE THREAD

**Issue by rustomax** [FedericoCeratto/nim-package-directory#6]
Showing broken links. Reproducible in Safari and Chrome.
![image](https://user-images.githubusercontent.com/20992642/34806611-e7654be0-f651-11e7-8599-6a9d5cb28582.png)
![image](https://user-images.githubusercontent.com/20992642/34806620-f6aff438-f651-11e7-8f07-975099443c27.png)

**Comment by polypus74** [comment]
Is this a hosting issue? Has anyone looked into it? I also often get a server error and pages fail to load entirely.

**Comment by rustomax** [comment]
I believe this has been fixed
