### ISSUE TITLE
[FR] Automatically cache source code of packages?

### ISSUE THREAD

**Issue by sgmihai** [FedericoCeratto/nim-package-directory#64]
Was looking forward to use https://nimble.directory/pkg/nimqbittorrent but it seems the repo has been deleted by the author. archive.org didn't archive the source files. Domain of contact e-mail for author is expired. Maybe RIP, who knows.
Would be nice if we had a snapshot of the git source code in nimble directory for situations like these. If your project depends on a nimble package that gets nuked by the author and you don't have the code anymore for some reason, you're doomed. Not sure if this is the right repo  to request this.

**Comment by FedericoCeratto** [comment]
Thanks. This has been discussed in the past and it would require significant effort as it creates a distribution of its own.
There's been also talks about doing a distribution of selected packages together with compiler releases but went nowhere unfortunately. A related issue has been opened but never attracted support: https://github.com/nim-lang/RFCs/issues/179
I am going to close this issue as this is a broad issue that goes beyond the scope of this project.
