### ISSUE TITLE
finding number of nim packages can be confusing

### ISSUE THREAD

**Issue by timotheecour** [FedericoCeratto/nim-package-directory#7]
reposting from https://github.com/nim-lang/Nim/issues/7410#issuecomment-375931490 to here since this seems the right project.

This came up in https://github.com/timotheecour/D_vs_nim/issues/3

for someone not very familiar with nim trying to figure out how many packages does nim have, things can be confusing:

https://nimble.directory/packages.xml shows only ~194 packages but https://github.com/nim-lang/packages shows ~640 packages

it's made worse by the fact that https://github.com/nim-lang/Nim/issues/7400 still prevents someone browsing https://nim-lang.org/docs/lib.html from seeing packages, and the fact that https://nimble.directory/ doesn't show the total number of packages.

https://nimble.directory/packages.xml
shows:
```
<description>New and updated Nim packages</description>
    <link>https://nimble.directory/packages.xml</link>
    <lastBuildDate></lastBuildDate>
    <pubDate></pubDate>
    <ttl>3600</ttl>
```
but doesn't specify what it means by `new and updated`; 

how about:
* specify total number of packages in https://nimble.directory/ (or maybe total + total new since <date>), eg as done in https://code.dlang.org/ which shows `Displaying results 1 to 21 of 1250 packages found.`

* change description in https://nimble.directory/packages.xml to show: `New and updated Nim packages since <date>`

**Comment by euantorano** [comment]
For future reference, Nimble pulls from https://github.com/nim-lang/packages and as such, that repository is the best place to get the count from.

**Comment by FedericoCeratto** [comment]
https://nimble.directory/packages.xml  is an RSS feed to announce the publication of new packages and it's not meant to list all existing packages.

**Comment by FedericoCeratto** [comment]
Added package count on /api/v1/package_count in https://github.com/FedericoCeratto/nim-package-directory/commit/511d4957cc580b839a35393eb361d244d7d75ae0
